"use strict";

export default {
  SEARCH_PLANETS: 'SEARCH_PLANETS',
  FILTER_PLANETS: 'FILTER_PLANETS',
  CHECK_USER_AUTH: 'CHECK_USER_AUTH',
  USER_AUTH_FAILED: 'USER_AUTH_FAILED',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_CHANGE_EVENT: 'USER_AUTH_CHANGE_EVENT',
  USER_LOGIN_AUTH_CHANGE_EVENT: 'USER_LOGIN_AUTH_CHANGE_EVENT',
  CHANGE_EVENT: 'SEARCH_PLANETS_CHANGE_EVENT'
};
